var ExpandData = {  
   "thead":{  
      "tr":[
        {  
        "th":[ 
           {  
               "text":""
           },
           {  
               "text":"NAME",
               "sort":{
                   "key":"name",
                   "direction":"asc"
               }
           },
           {  
              "text":"EMAIL",
              "sort":{
                  "key":"email"
              }
           },
           {  
              "text":"ROLE",
              "sort":{
                  "key":"role"
              }
           },
           {  
              "text":"DIVISION",
              "sort":{
                  "key":"division"
              }
           },
           {  
              "text":"# LOGINS",
              "sort":{
                  "key":"login_count"
              }
           },
           {  
              "text":"LAST LOGIN",
              "sort":{
                  "key":"last_login"
              }
           },
           {  
              "text":"ACTIONS"
           }
        ],
        "style":""
    }
    ]
   },
   "tbody":{  
      "tr":[  
         {  
            "td":[  
                {  
                    "text":"",
                    "style":{
                        "padding":"0px"
                    },
                    "expandable":true
                },
                {  
                  "text":"Anne Fedi"
               },
               {  
                  "text":"anne_fedi@ses.dta.customergauge.com"
               },
               {  
                  "text":"User"
               },
               {  
                  "text":"Global"
               },
               {  
                  "text":8
               },
               {  
                  "text":"2019-02-04 11:45:41"
               },
               {  
                  "text":""
               }
            ],
            "style":"",
            "expand":{
                "status":false,
                "component":{
                    "name":"UserDetails",
                    "data": {
                        "description":"This is a test user.",
                        "id":8
                    }
                }
            }
         },
         {  
            "td":[  
                {  
                    "text":"",
                    "style":{
                        "padding":"0px"
                    },
                    "expandable":true
                },
                {  
                  "text":"Gavin Striegler"
               },
               {  
                  "text":"gavin_striegler@ses.dta.customergauge.com"
               },
               {  
                  "text":"Admin"
               },
               {  
                  "text":"APAC"
               },
               {  
                  "text":25
               },
               {  
                  "text":"2018-09-27 08:58:48"
               },
               {  
                  "text":""
              }
            ],
            "style":"",
            "expand":{
                "status":false,
                "component":{
                    "name":"UserDetails",
                    "data": {
                        "description":"This is a test user.",
                        "id":25
                    }
                }
            }
         },
         {  
            "td":[  
                {  
                    "text":"",
                    "style":{
                        "padding":"0px"
                    },
                    "expandable":true
                },
                {  
                  "text":"Stella Wohlfeil",
                  "style":{  
                     "color":"#aaa"
                  }
               },
               {  
                  "text":"stella_wohlfeil@ses.dta.customergauge.com",
                  "style":{  
                     "color":"#aaa"
                  }
               },
               {  
                  "text":"User",
                  "style":{  
                     "color":"#aaa"
                  }
               },
               {  
                  "text":"Global",
                  "style":{  
                     "color":"#aaa"
                  }
               },
               {  
                  "text":19,
                  "style":{  
                     "color":"#aaa"
                  }
               },
               {  
                  "text":"2019-05-16 13:50:07",
                  "style":{  
                     "color":"#aaa"
                  }
               },
               {  
                  "text":""
              }
            ],
            "style":"",
            "expand":{
                "status":false,
                "component":{
                    "name":"UserDetails",
                    "data": {
                        "description":"This is a test user.",
                        "id":19
                    }
                }
            }
         },
         {  
            "td":[  
                {  
                    "text":"",
                    "style":{
                        "padding":"0px"
                    },
                    "expandable":true
                },
                {  
                  "text":"Nicola Frauendorf"
               },
               {  
                  "text":"nicola_frauendorf@ses.dta.customergauge.com"
               },
               {  
                  "text":"Admin"
               },
               {  
                  "text":"EMEA"
               },
               {  
                  "text":74
               },
               {  
                  "text":"2019-03-07 10:18:35"
               },
               {  
                  "text":""
               }
            ],
            "style":"",
            "expand":{
                "status":false,
                "component":{
                    "name":"UserDetails",
                    "data": {
                        "description":"This is a test user.",
                        "id":74
                    }
                }
            }
         },
         {  
            "td":[  
                {  
                    "text":"",
                    "style":{
                        "padding":"0px"
                    },
                    "expandable":true
                },
                {  
                  "text":"JP Tognon"
               },
               {  
                  "text":"jp_tognon@ses.dta.customergauge.com"
               },
               {  
                  "text":"Admin"
               },
               {  
                  "text":"Global"
               },
               {  
                  "text":43
               },
               {  
                  "text":"2018-11-01 16:47:08"
               },
               {  
                  "text":""
              }
            ],
            "style":"",
            "expand":{
                "status":false,
                "component":{
                    "name":"UserDetails",
                    "data": {
                        "description":"This is a test user.",
                        "id":43
                    }
                }
            }
         }
      ]
  }
}

export default ExpandData;